addons:
    apt:
        packages:
            - python-pygments
            
install:
    - rm -rf public  || exit 0
    
script:
    - hugo

git:
    submodules: true

branches:
    only:
        - master
  
deploy:
    provider: pages
    skip_cleanup: true
    local_dir: public
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
        branch: master
  
#  after_success:
#- mkdir .deploy
#- cd .deploy
#- git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add -t gh-pages origin $DEPLOY_REPO)
#- rm -rf ./*
#- cp -r ../public/* .
#- git add -A .
#- git commit -m 'Automatic publish with Travis-CI'
#- git branch -m gh-pages
#- git push -q -u origin gh-pages
